### PR TITLE
Feature/179434417 add more download files for pride rebased

### PR DESCRIPTION
**Pull request by lingyun1010**
This PR is companied with [atlas-web-core PR](https://github.com/ebi-gene-expression-group/atlas-web-core/pull/78)

We add two more files for proteomic experiment

    the unprocessed raw output file (accession-proteinGroups.txt)
    the parameter file (accession.mqpar.xml)

### CODE REVIEW

**Review by upendrakumbham — COMMENTED** [review]
Please provide testing steps to test when I run this branch in my machine. What we are expecting to see as part of this. Any data configuration to test PR?

**Review by alfonsomunozpomer — CHANGES_REQUESTED** [review]
All fine, just fix the typos in several places, `qaunt` -> `quant`

**Review by upendrakumbham — APPROVED** [review]
All Good, please merge away.

**Comment by pcm32** [comment]
For who reviews this PR, please make sure that commit e22b44e is reverted, as this in the current shape will:

- get rid of the CI compilation test (which aims to pick up missing or misaligned revisions of web-core)
- get rid of operations that we need for the CLI

and of course these two shouldn't happen. Also, this, as any other PR, needs to pass the CI compilation test, or it cannot be merged. If that happens it will mean that develop will be in a non-compilable state, which is problematic for starting any feature branch from there.

**Pull request merged**
