### PR TITLE
179434417 add more download files for pride cleaned

### PR DESCRIPTION
**Pull request by lingyun1010**
This PR is a cleaned version for an old bulk [PR](https://github.com/ebi-gene-expression-group/atlas-web-bulk/pull/93) 

We add two more files for proteomic experiment

the unprocessed raw output file (accession-proteinGroups.txt)
the parameter file (accession.mqpar.xml)

### CODE REVIEW

**Review by alfonsomunozpomer — APPROVED** [review]
LGTM.

**Comment by pcm32** [comment]
Why are we merging branches if the compilation doesn't pass?

**Comment by pcm32** [comment]
This means that someone else will have to fix those issues in their local machine. This is easily 3rd time it occurs in less than 2 weeks.

**Comment by lingyun1010** [comment]
The issue was due to I did not pull the latest commit in my `atlas-web-core` before merging core, but it won't be an issue for developers if they pull or rebase the latest branch, if I don't misunderstand.

**Pull request merged**
