### PR TITLE
CI test for WAR compilation

### PR DESCRIPTION
**Pull request by pcm32**
This PR adds a github actions CI to check that the web application WAR compilation works.

### CODE REVIEW

**Review by alfonsomunozpomer — APPROVED** [review]
Thanks for adding this.

**Comment by alfonsomunozpomer** [comment]
We’ve got an issue with the custom Solr packages. We need to wait until our Artifactory instance is available.

**Comment by pcm32** [comment]
Lets merge this after the artifactory situation is resolved.

**Review by alfonsomunozpomer — APPROVED** [review]
All good now! Please merge.

**Pull request merged**
