### PR TITLE
Add a more sophisticated mechanism to link experiments

### LINKED ISSUE #140: Add a more sophisticated mechanism to link experiments
Currently an experiment can be linked to another using the factors XML file with the filed `<alternativeView>`. Because we’ll be adding links to different types of experiment, rather than “View by...” we should change the text to to “See proteomics experiment” if the accession is of a different type than the current experiment.

E-MTAB-2836 links to E-PROT-29.

### PR DESCRIPTION
**Pull request by lingyun1010**
In bulk experiment  page, there are some experiments have alternative views, such as E-MTAB-5200 and E-MTAB-5423.

If the source and destination experiment types (according to accessions) are different, show link as `Related <proteomics/transcriptomics> experiment`, otherwise keep the current format (View by <keyword>).

Due to lacking good examples in local files, I tested experiment `E-MTAB-5200` with an alternative view `E-PROT-1` locally, as shown below:
Screenshot 2022-09-13 at 08 56 37

While normally it is `View by individual`, check below:
https://www.ebi.ac.uk/gxa/experiments/E-MTAB-5200/Results

### CODE REVIEW

**Review by haideriqbal — CHANGES_REQUESTED** [review]
I see there are only web-core commits in this PR and upon checking atlas-web-core I cannot see any related PR there. Can you please create a sister PR in atlas-web-core and then link it here?

**Comment by lingyun1010** [comment]
@haideriqbal The sister web core PR is https://github.com/ebi-gene-expression-group/atlas-web-core/pull/113.

**Comment by haideriqbal** [comment]
> @haideriqbal The sister web core PR is [ebi-gene-expression-group/atlas-web-core#113](https://github.com/ebi-gene-expression-group/atlas-web-core/pull/113).

@lingyun1010 please look into this branch and rebase/update it accordingly, because it contains quite a few changes in web-core which are not mentioned in your `atlas-web-core` PR. I assume this branch needs to be updated to properly reflect the changes you made in `atlas-web-core`.

**Comment by alfonsomunozpomer** [comment]
@lingyun1010 @haideriqbal Can’t you see something that can be clearly improved in the screenshot?

**Comment by haideriqbal** [comment]
> @lingyun1010 @haideriqbal Can’t you see something that can be clearly improved in the screenshot?

The experiment type is being displayed in the label which the user would not be able to make sense of. `PROTEOMICS_BASELINE_DIA` should be transformed into `Proteomics`.

**Comment by lingyun1010** [comment]
> @lingyun1010 @haideriqbal Can’t you see something that can be clearly improved in the screenshot?

Okay I see, then maybe the `humanDescription` defined in `ExperimentType` will work?
In this case, it would be `Proteomics baseline DIA`.

**Pull request merged**
