### PR TITLE
Fix docker compose files for local env

### PR DESCRIPTION
**Pull request by ke4**
Changes:
- Fix the service, volume names and also correct the attached volumes for Tomcat service
- Add a shell script that builds and deploys the web app
- Improve the build-and-deploy-webapp shell script
  - Added different flags to the build-and-deploy-webapp.sh shell script to be able to build only front or back-end part of the application or both of them.
  - Also added a usage/help file to the script.
  - Added its usage to the README.

### CODE REVIEW

**Comment by upendrakumbham** [comment]
I have tested this PR in my local environment, all the docker-compose issues got fixed,  I'm able to run all the containers successfully without issues.

**Comment by upendrakumbham** [comment]
When I ran the application in my local:  `http://localhost:8080/gxa`, I got the below error:

image

**Comment by upendrakumbham** [comment]
@lingyun1010, if we both are on the same page, probably we need to fix this by running Magetab/Postgres volume scripts.

**Comment by lingyun1010** [comment]
I got errors while running the solr docker volume populating command. The `depends on` services names are not found, which should be fixed too as the postgres one. 
```    
depends_on:
      - postgres
      - solrcloud-0
      - solrcloud-1
```

**Comment by lingyun1010** [comment]
> When I ran the application in my local: `http://localhost:8080/gxa`, I got the below error:
> 
> image

@upendrakumbham did you repopulate docker volume before starting the service in this case?

**Comment by ke4** [comment]
> I got errors while running the solr docker volume populating command. The `depends on` services names are not found, which should be fixed too as the postgres one.
> 
> ```
> depends_on:
>       - postgres
>       - solrcloud-0
>       - solrcloud-1
> ```

@lingyun1010 There are no dependent services in the `volumes-populator` service. Are you sure about the above?

**Comment by ke4** [comment]
> When I ran the application in my local: `http://localhost:8080/gxa`, I got the below error:
> 
> image

@upendrakumbham We don't have `E-MTAB-5423` experiment in our local environment. I suppose, your DB got corrupted or was not clean and not executed all the steps described in the `README` file.

**Comment by lingyun1010** [comment]
@ke4 I've tested with the latest commits, but I still cannot populate the solr database in docker, having the error message below 
```  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: solrcloud-0
solr-populator-1           | ls: cannot access '/root/experiments-jsonl/*.jsonl': No such file or directory
solr-populator-1 exited with code 0
```
I don't know if you can populate the data properly on your side or on @upendrakumbham side.

**Comment by ke4** [comment]
I am going to merge this PR as we discussed it with @lingyun1010 earlier today.

**Pull request merged**
