### PR TITLE
Feature/180083715 rename pdf file for download

### PR DESCRIPTION
**Pull request by lingyun1010**
Please be aware that this PR will also include the commits that were missing in the implementation of add pdf summary file.

This story is to add summary pdf file into experiment download section.

The filenames could be: `E-PROT-59-Summary_ExpressionAtlas.pdf` or `E-PROT-63-MaxQuant_Summary_ExpressionAtlas.pdf`

### CODE REVIEW

**Comment by upendrakumbham** [comment]
1.

image

2.

image

This is the result I got after updating the summary pdf. I'm expecting an experiment accession as a prefix for the summary pdf.

**Comment by lingyun1010** [comment]
> image
> 
> 
> image
> 
> This is the result I got after updating the summary pdf. I'm expecting an experiment accession as a prefix for the summary pdf.

Not exactly. In the download page, we only need for show `Summary pdf`, which is enough.

**Comment by upendrakumbham** [comment]
Thanks, @lingyun1010 for the clarification. I will approve PR as it is working as expected.

**Review by upendrakumbham — APPROVED** [review]
Tested PR, working as expected. Please merge away.

**Pull request merged**
